version: '3.4'

services:
  mygithublibrary:
    image: ${DOCKER_REGISTRY-}mygithublibrary
    build:
      context: .
      dockerfile: MyGitHubLibrary/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80/;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SECRETPASSWORD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - mygithublibrarynetwork

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "mygithublibrary"
      POSTGRES_PASSWORD: "mygithublibrary"
      POSTGRES_DB: "MyGitHubLibrary"
    ports:
      - "15432:5432" 
    volumes:
      - "./Scripts.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - mygithublibrarynetwork
    restart: always
    
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rogertostes@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "mygithublibrary"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - mygithublibrarynetwork
    restart: always

networks: 
  mygithublibrarynetwork:
    driver: bridge
